# Generated by Django 4.2.30 on 2026-07-18 00:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_module', '0002_remove_userservicelocation_unique_user_service_location_and_more'),
        ('items', '0002_alter_item_name'),
        ('vendors', '0002_alter_vendor_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'db_table': 'aggregated_order_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked out'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='OrderCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateField()),
                ('order_window_start', models.DateTimeField()),
                ('order_window_end', models.DateTimeField()),
                ('quote_window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('quoting', 'Quoting'), ('vendor_selected', 'Vendor selected'), ('placed', 'Placed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cycles', to='location_module.servicelocation')),
            ],
            options={
                'db_table': 'order_cycles',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('acknowledged', 'Acknowledged'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='ordering.ordercycle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ordering.cart')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to='ordering.ordercycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('partially_selected', 'Partially selected'), ('selected', 'Selected')], default='invited', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_quotes', to='ordering.ordercycle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_quotes',
            },
        ),
        migrations.CreateModel(
            name='VendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.vendorquote')),
            ],
            options={
                'db_table': 'vendor_quote_items',
            },
        ),
        migrations.CreateModel(
            name='UserOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.userorder')),
            ],
            options={
                'db_table': 'user_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('aggregated_order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_item', to='ordering.aggregatedorderitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='ordering.ordercycle'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aggregatedorderitem',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregated_items', to='ordering.ordercycle'),
        ),
        migrations.AddField(
            model_name='aggregatedorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item'),
        ),
        migrations.AddField(
            model_name='aggregatedorderitem',
            name='selected_quote_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for', to='ordering.vendorquoteitem'),
        ),
        migrations.AddConstraint(
            model_name='vendorquoteitem',
            constraint=models.UniqueConstraint(fields=('quote', 'item'), name='unique_vendor_quote_item'),
        ),
        migrations.AddConstraint(
            model_name='vendorquote',
            constraint=models.UniqueConstraint(fields=('cycle', 'vendor'), name='unique_vendor_quote_cycle'),
        ),
        migrations.AddConstraint(
            model_name='userorderitem',
            constraint=models.UniqueConstraint(fields=('user_order', 'item'), name='unique_user_order_item'),
        ),
        migrations.AddConstraint(
            model_name='userorder',
            constraint=models.UniqueConstraint(fields=('cycle', 'user'), name='one_order_per_user_cycle'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('cycle', 'vendor'), name='unique_po_cycle_vendor'),
        ),
        migrations.AddIndex(
            model_name='ordercycle',
            index=models.Index(fields=['service_location', 'status'], name='order_cycle_service_0ca096_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercycle',
            constraint=models.UniqueConstraint(fields=('service_location', 'cycle_date'), name='unique_cycle_location_date'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'item'), name='unique_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('cycle', 'user'), name='one_active_cart_per_user_cycle'),
        ),
        migrations.AddConstraint(
            model_name='aggregatedorderitem',
            constraint=models.UniqueConstraint(fields=('cycle', 'item'), name='unique_aggregated_item'),
        ),
    ]
