# Generated by Django 4.2.30 on 2026-06-26 18:27

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
                'db_table': 'service_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='location_module.servicelocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Service Location',
                'verbose_name_plural': 'User Service Locations',
                'db_table': 'user_service_locations',
                'ordering': ['user', 'service_location'],
            },
        ),
        migrations.AddConstraint(
            model_name='userservicelocation',
            constraint=models.UniqueConstraint(fields=('user', 'service_location'), name='unique_user_service_location'),
        ),
    ]
