# Generated by Django 4.2.30 on 2026-06-27 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userservicelocation',
            name='unique_user_service_location',
        ),
        migrations.AlterField(
            model_name='userservicelocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
