# Generated by Django 4.2.30 on 2026-07-04 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_module', '0002_remove_userservicelocation_unique_user_service_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(db_column='vendor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_service_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_vendors', to='location_module.servicelocation')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorServiceableLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceable_vendors', to='location_module.servicelocation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceable_locations', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Serviceable Location',
                'verbose_name_plural': 'Vendor Serviceable Locations',
                'db_table': 'vendor_serviceable_locations',
                'ordering': ['vendor', 'service_location'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorserviceablelocation',
            constraint=models.UniqueConstraint(fields=('vendor', 'service_location'), name='unique_vendor_serviceable_location'),
        ),
    ]
