# Generated by Django 4.2.30 on 2026-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default="1234567890", max_length=20),
            preserve_default=False,
        ),
    ]
