# Generated by Django 4.2.30 on 2026-07-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_alter_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='partner_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='items.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_items',
            },
        ),
        migrations.AddConstraint(
            model_name='vendoritem',
            constraint=models.UniqueConstraint(fields=('vendor', 'item'), name='unique_vendor_item'),
        ),
    ]
